### ISSUE TITLE
BunPro: Redundant answer bug

### ISSUE THREAD

**Issue by Aarixx** [ezhmd/anki-mode#3]
![Bunrpo](https://user-images.githubusercontent.com/40311357/58763707-805acb80-852c-11e9-86af-40ee9f81628d.jpg)

For answers that appear twice in a sentence, showing answer takes both into the answer field causing the user to need to delete the 2nd half of the answer for it to be accepted.

![image](https://user-images.githubusercontent.com/40311357/58763721-cfa0fc00-852c-11e9-9776-6d6333f45acd.png)

Looks like perhaps rejecting the second "study-area-input" should take care of it.

I wasn't able to do a dirty fix by adding this to the function:

$(".anki-show").click(function() {
  
  if($("#study-answer-input").val($("そうそう"))){
	$("#study-answer-input").val("そう");
      	}
    
	$("#show-answer").click();
	
  $("#study-answer-input").val($(".study-area-input").text());
	
});

So My work around was just adding a button to do it for me

**Comment by echamudi** [comment]
Hello Aarixx,
Thanks for noticing the problem.

From your description, I guess this might solve the problem. Instead of:
```js
$("#study-answer-input").val($(".study-area-input").text());
```
use this
```js
$("#study-answer-input").val($(".study-area-input").first().text());
```
This new line will only select the first `study-area-input` element and get the text.

It's kinda not easy to test this case as we rarely encounter this question. 
Please try in your side and kindly tell me if it works :).

**Comment by echamudi** [comment]
I've tested it and updated the code. It seems working fine now for this kind of question.

Cheers.
